- name: jitsi_videobridge_total_conferences_created
  path: $.total_conferences_created
- name: jitsi_videobridge_total_ice_failed
  path: $.total_ice_failed
- name: jitsi_videobridge_threads
  path: $.threads
- name: jitsi_videobridge_videochannels
  path: $.videochannels
- name: jitsi_videobridge_total_packets_received_octo
  path: $.total_packets_received_octo
- name: jitsi_videobridge_octo_receive_packet_rate
  path: $.octo_receive_packet_rate
- name: jitsi_videobridge_total_bytes_received
  path: $.total_bytes_received
- name: jitsi_videobridge_rtp_loss
  path: $.rtp_loss
- name: jitsi_videobridge_total_loss_controlled_participant_seconds
  path: $.total_loss_controlled_participant_seconds
- name: jitsi_videobridge_total_partially_failed_conferences
  path: $.total_partially_failed_conferences
- name: jitsi_videobridge_endpoints_sending_audio
  path: $.endpoints_sending_audio
- name: jitsi_videobridge_total_bytes_sent
  path: $.total_bytes_sent
- name: jitsi_videobridge_mucs_configured
  path: $.mucs_configured
- name: jitsi_videobridge_total_failed_conferences
  path: $.total_failed_conferences
- name: jitsi_videobridge_mucs_joined
  path: $.mucs_joined
- name: jitsi_videobridge_videostreams
  path: $.videostreams
- name: jitsi_videobridge_jitter_aggregate
  path: $.jitter_aggregate
- name: jitsi_videobridge_total_ice_succeeded_tcp
  path: $.total_ice_succeeded_tcp
- name: jitsi_videobridge_octo_endpoints
  path: $.octo_endpoints
- name: jitsi_videobridge_total_packets_dropped_octo
  path: $.total_packets_dropped_octo
- name: jitsi_videobridge_conferences
  path: $.conferences
- name: jitsi_videobridge_participants
  path: $.participants
- name: jitsi_videobridge_largest_conference
  path: $.largest_conference
- name: jitsi_videobridge_total_packets_sent
  path: $.total_packets_sent
- name: jitsi_videobridge_total_data_channel_messages_sent
  path: $.total_data_channel_messages_sent
- name: jitsi_videobridge_total_bytes_received_octo
  path: $.total_bytes_received_octo
- name: jitsi_videobridge_octo_send_packet_rate
  path: $.octo_send_packet_rate
- name: jitsi_videobridge_total_packets_sent_octo
  path: $.total_packets_sent_octo
- name: jitsi_videobridge_inactive_endpoints
  path: $.inactive_endpoints
- name: jitsi_videobridge_inactive_conferences
  path: $.inactive_conferences
- name: jitsi_videobridge_total_ice_succeeded_relayed
  path: $.total_ice_succeeded_relayed
- name: jitsi_videobridge_total_loss_degraded_participant_seconds
  path: $.total_loss_degraded_participant_seconds
- name: jitsi_videobridge_bit_rate_download
  path: $.bit_rate_download
- name: jitsi_videobridge_muc_clients_connected
  path: $.muc_clients_connected
- name: jitsi_videobridge_total_participants
  path: $.total_participants
- name: jitsi_videobridge_total_packets_received
  path: $.total_packets_received
- name: jitsi_videobridge_rtt_aggregate
  path: $.rtt_aggregate
- name: jitsi_videobridge_packet_rate_upload
  path: $.packet_rate_upload
- name: jitsi_videobridge_p2p_conferences
  path: $.p2p_conferences
- name: jitsi_videobridge_total_loss_limited_participant_seconds
  path: $.total_loss_limited_participant_seconds
- name: jitsi_videobridge_octo_send_bitrate
  path: $.octo_send_bitrate
- name: jitsi_videobridge_total_dominant_speaker_changes
  path: $.total_dominant_speaker_changes
- name: jitsi_videobridge_receive_only_endpoints
  path: $.receive_only_endpoints
- name: jitsi_videobridge_total_colibri_web_socket_messages_received
  path: $.total_colibri_web_socket_messages_received
- name: jitsi_videobridge_octo_receive_bitrate
  path: $.octo_receive_bitrate
- name: jitsi_videobridge_loss_rate_upload
  path: $.loss_rate_upload
- name: jitsi_videobridge_total_ice_succeeded
  path: $.total_ice_succeeded
- name: jitsi_videobridge_total_colibri_web_socket_messages_sent
  path: $.total_colibri_web_socket_messages_sent
- name: jitsi_videobridge_total_bytes_sent_octo
  path: $.total_bytes_sent_octo
- name: jitsi_videobridge_total_data_channel_messages_received
  path: $.total_data_channel_messages_received
- name: jitsi_videobridge_loss_rate_download
  path: $.loss_rate_download
- name: jitsi_videobridge_total_conference_seconds
  path: $.total_conference_seconds
- name: jitsi_videobridge_bit_rate_upload
  path: $.bit_rate_upload
- name: jitsi_videobridge_total_conferences_completed
  path: $.total_conferences_completed
- name: jitsi_videobridge_octo_conferences
  path: $.octo_conferences
- name: jitsi_videobridge_num_eps_no_msg_transport_after_delay
  path: $.num_eps_no_msg_transport_after_delay
- name: jitsi_videobridge_endpoints_sending_video
  path: $.endpoints_sending_video
- name: jitsi_videobridge_packet_rate_download
  path: $.packet_rate_download
- name: jitsi_videobridge_muc_clients_configured
  path: $.muc_clients_configured